baseURL = 'https://blog.vmeta.jp/'
languageCode = 'ja'
title = "meta's blog - The Power To Serve"
#theme = 'hugo-geekblog'
theme = 'roadster'
#theme = 'hugo-clarity'
timeZone = 'Asia/Tokyo'

hasCJKLanguage = true
defaultContentLanguage = 'ja'
enableRobotsTXT = true

googleAnalytics = 'G-ZWQ5RPWV31'

[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^vim$']

# 生HTML埋め込みを許可
[markup.goldmark.renderer]
unsafe = true

[Params]
post_meta = [ 'date' ]
dateFormat = '2006-01-02'
pager = true

[Params.sidebar]
home = 'right'
single = 'right'
list = 'right'

widgets = [ 'search', 'recent', 'taglist', 'social' ]

[Params.widgets]
tags_counter = true

[Params.widgets.search.input]
name = "sitesearch"
pre = "blog.vmeta.jp"

[Params.widgets.social]
github = 'metalefty'

[Params.style.vars]
highlightColor = '#5690BE'
